### ISSUE TITLE
[WinError 10054] An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by Arxcis** [Arxcis/MultiplayerTurtles#1]
Har fått kontakt med serveren, men det virker som at koden i serveren ikke fungere slik den skal.

Fra kommando-linjen til klienten:
........
Started the thread
connected to server 127.0.0.1 1337
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python35-32\lib\threading.py", line 914, in _bootstrap_inner
    self.run()
  File "C:\Python35-32\lib\threading.py", line 862, in run
    self._target(_self._args, *_self._kwargs)
  File "C:\Users\Jonas\Desktop\Multiturtles\networks.py", line 26, in listen_to_server
    message = s.recv(1024).decode(encoding='utf-8')
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by Arxcis** [comment]
Dette skjer fordi jeg prøvde å kjøre både server og client i samme sublime vindu. Når client startet så stengte serveren seg.

Jeg løste dette ved å åpne 2 git-bash vinduer. Kjørte server i det ene vinduet og client i det andre.
